/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTVector2f */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTVector2f
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTVector2f
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2f
 * Method:    length
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2f_length
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2f
 * Method:    subtract
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;)Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2f_subtract
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
