/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTScreenshot */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
 * Method:    GetWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot_GetWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
 * Method:    GetHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot_GetHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
 * Method:    GetPixelColorAt
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot_GetPixelColorAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
 * Method:    SaveAsBitmap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot_SaveAsBitmap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
 * Method:    CompareToImage
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot_CompareToImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTScreenshot
 * Method:    SimmilarityBetweenImagesShouldBe
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTScreenshot_SimmilarityBetweenImagesShouldBe
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
