/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTMouse */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTMouse
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTMouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    GetPosition
 * Signature: ()Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_GetPosition
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    MoveMouse
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_MoveMouse
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    SetPosition
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_SetPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    ClickLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_ClickLeft
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    ClickRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_ClickRight
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    ClickMiddle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_ClickMiddle
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    PressLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_PressLeft
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    PressMiddle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_PressMiddle
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    PressRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_PressRight
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    ReleaseLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_ReleaseLeft
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    ReleaseMiddle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_ReleaseMiddle
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    ReleaseRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_ReleaseRight
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    Scroll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_Scroll
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    SetPositionRelativeToWindow
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTWindow;Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_SetPositionRelativeToWindow__Lorg_filomilo_GuiTestingLibrary_Native_JGTWindow_2Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2i_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    SetPositionRelativeToWindow
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTWindow;Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_SetPositionRelativeToWindow__Lorg_filomilo_GuiTestingLibrary_Native_JGTWindow_2Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2f_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    PositionShouldBe
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;I)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_PositionShouldBe
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    MoveMouseTo
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_MoveMouseTo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    MoveMouseRelativeToWindowTo
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTWindow;Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_MoveMouseRelativeToWindowTo__Lorg_filomilo_GuiTestingLibrary_Native_JGTWindow_2Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2i_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    MoveMouseRelativeToWindowTo
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTWindow;Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_MoveMouseRelativeToWindowTo__Lorg_filomilo_GuiTestingLibrary_Native_JGTWindow_2Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2f_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    GetPositionRelativeToWindow
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTWindow;)Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_GetPositionRelativeToWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTMouse
 * Method:    PositionRelativeToWindowShouldBe
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTWindow;Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;F)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTMouse_PositionRelativeToWindowShouldBe
  (JNIEnv *, jobject, jobject, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
