/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTSystem */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTSystem
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTSystem
 * Method:    GetClipBoardContent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTSystem_GetClipBoardContent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
