/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_NativeGtSystem */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_NativeGtSystem
#define _Included_org_filomilo_GuiTestingLibrary_Native_NativeGtSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_NativeGtSystem
 * Method:    GetClipBoard
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_filomilo_GuiTestingLibrary_Native_NativeGtSystem_GetClipBoard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
