namespace gui_tesing_library.Models
{
    public enum Key
    {
        //KEY_TAB = '	',
        //KEY_ENTER = '\n',
        //KEY_BACKSPACE = '\b',
        //KEY_SPACE = ' ',
        //KEY_EXCLAMAITION_MARK = '!',
        //KEY_QUOATE = '\"',
        //KEY_HASHTAG = '#',
        //KEY_DOLAR = '$',
        //KEY_PROCENT = '%',
        //KEY_AMPERSAND = '&',
        //KEY_MINI_QUOTE = '\'',
        //KEY_BRACKET_LEFT = '(',
        //KEY_BRACKET_RIGHT = ')',
        //KEY_STAR = '*',
        //KEY_PLUS = '+',
        //KEY_COMA = ',',
        //KEY_MINUS = '-',
        //KEY_DOT = '.',
        //KEY_SLASH_RIGHT = '/',
        //KEY_0 = '0',
        //KEY_1 = '1',
        //KEY_2 = '2',
        //KEY_3 = '3',
        //KEY_4 = '4',
        //KEY_5 = '5',
        //KEY_6 = '6',
        //KEY_7 = '7',
        //KEY_8 = '8',
        //KEY_9 = '9',
        //KEY_COLON = ':',
        //KEY_SEMICOLON = ';',
        //KEY_LESS_THAN = '<',
        //KEY_EQUAL = '=',
        //KEY_MORE_THAN = '>',
        //KEY_QUESTION = '?',
        //KEY_COMMERCIAL = '@',
        //KEY_A = 'A',
        //KEY_B = 'B',
        //KEY_C = 'C',
        //KEY_D = 'D',
        //KEY_E = 'E',
        //KEY_F = 'F',
        //KEY_G = 'G',
        //KEY_H = 'H',
        //KEY_I = 'I',
        //KEY_J = 'J',
        //KEY_K = 'K',
        //KEY_L = 'L',
        //KEY_M = 'M',
        //KEY_N = 'N',
        //KEY_O = 'O',
        //KEY_P = 'P',
        //KEY_Q = 'Q',
        //KEY_R = 'R',
        //KEY_S = 'S',
        //KEY_T = 'T',
        //KEY_U = 'U',
        //KEY_V = 'V',
        //KEY_W = 'W',
        //KEY_X = 'X',
        //KEY_Y = 'Y',
        //KEY_Z = 'Z',
        //KEY_SQUARE_BRACKET_LEFT = '[',
        //KEY_SLASH_LEFT = '\\',
        //KEY_SQUARE_BRACKET_RIGHT = ']',
        //KEY_CIRCUMFLEX = '^',
        //KEY__ = '_',
        //KEY_GRAVE = '`',
        //KEY_a = 'a',
        //KEY_b = 'b',
        //KEY_c = 'c',
        //KEY_d = 'd',
        //KEY_e = 'e',
        //KEY_f = 'f',
        //KEY_g = 'g',
        //KEY_h = 'h',
        //KEY_i = 'i',
        //KEY_j = 'j',
        //KEY_k = 'k',
        //KEY_l = 'l',
        //KEY_m = 'm',
        //KEY_n = 'n',
        //KEY_o = 'o',
        //KEY_p = 'p',
        //KEY_q = 'q',
        //KEY_r = 'r',
        //KEY_s = 's',
        //KEY_t = 't',
        //KEY_u = 'u',
        //KEY_v = 'v',
        //KEY_w = 'w',
        //KEY_x = 'x',
        //KEY_y = 'y',
        //KEY_z = 'z',
        //KEY_CURLY_BRACKET_LEFT = '{',
        //KEY_VERTICAL_LINE = '|',
        //KEY_CURLY_BRACKET_RIGHT = '}',
        //KEY_TILDE = '~',
        //KEY_INVERTED_EXCLAMATION_MARK = '¡',
        //KEY_CENT = '¢',
        //KEY_POUND = '£',
        //KEY_CURRENCY = '¤',
        //KEY_YEN = '¥',
        //KEY_BROKEN_BAR = '¦',
        //KEY_SECTION_SIGN = '§',
        //KEY_DIAERESIS = '¨',
        //KEY_COPYRIGHT = '©',
        //KEY_ª = 'ª',
        //KEY_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK = '«',
        //KEY_NOT_SIGN = '¬',
        //KEY_REGISTERED_SIGN = '®',
        //KEY_MACRON = '¯',
        //KEY_DEGREE = '°',
        //KEY_PLUS_MINUS_SIGN = '±',
        //KEY_SUPERSCRIPT_TWO = '²',
        //KEY_SUPERSCRIPT_THREE = '³',
        //KEY_ACUTE_ACCENT = '´',
        //KEY_µ = 'µ',
        //KEY_PILCROW_SIGN = '¶',
        //KEY_MIDDLE_DOT = '·',
        //KEY_CEDILLA = '¸',
        //KEY_SUPERSCRIPT_ONE = '¹',
        //KEY_º = 'º',
        //KEY_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK = '»',
        //KEY_VULGAR_FRACTION_ONE_QUARTER = '¼',
        //KEY_VULGAR_FRACTION_ONE_HALF = '½',
        //KEY_KEY_VULGAR_FRACTION_THRID_QUARTER = '¾',
        //KEY_INVERTED_QUESTION_MARK = '¿',
        //KEY_À = 'À',
        //KEY_Á = 'Á',
        //KEY_Â = 'Â',
        //KEY_Ã = 'Ã',
        //KEY_Ä = 'Ä',
        //KEY_Å = 'Å',
        //KEY_Æ = 'Æ',
        //KEY_Ç = 'Ç',
        //KEY_È = 'È',
        //KEY_É = 'É',
        //KEY_Ê = 'Ê',
        //KEY_Ë = 'Ë',
        //KEY_Ì = 'Ì',
        //KEY_Í = 'Í',
        //KEY_Î = 'Î',
        //KEY_Ï = 'Ï',
        //KEY_Ð = 'Ð',
        //KEY_Ñ = 'Ñ',
        //KEY_Ò = 'Ò',
        //KEY_Ó = 'Ó',
        //KEY_Ô = 'Ô',
        //KEY_Õ = 'Õ',
        //KEY_Ö = 'Ö',
        //KEY_MULTIPLICATION_SIGN = '×',
        //KEY_Ø = 'Ø',
        //KEY_Ù = 'Ù',
        //KEY_Ú = 'Ú',
        //KEY_Û = 'Û',
        //KEY_Ü = 'Ü',
        //KEY_Ý = 'Ý',
        //KEY_Þ = 'Þ',
        //KEY_ß = 'ß',
        //KEY_à = 'à',
        //KEY_á = 'á',
        //KEY_â = 'â',
        //KEY_ã = 'ã',
        //KEY_ä = 'ä',
        //KEY_å = 'å',
        //KEY_æ = 'æ',
        //KEY_ç = 'ç',
        //KEY_è = 'è',
        //KEY_é = 'é',
        //KEY_ê = 'ê',
        //KEY_ë = 'ë',
        //KEY_ì = 'ì',
        //KEY_í = 'í',
        //KEY_î = 'î',
        //KEY_ï = 'ï',
        //KEY_ð = 'ð',
        //KEY_ñ = 'ñ',
        //KEY_ò = 'ò',
        //KEY_ó = 'ó',
        //KEY_ô = 'ô',
        //KEY_õ = 'õ',
        //KEY_ö = 'ö',
        //KEY_DIVISION_SIGN = '÷',
        //KEY_ø = 'ø',
        //KEY_ù = 'ù',
        //KEY_ú = 'ú',
        //KEY_û = 'û',
        //KEY_ü = 'ü',
        //KEY_ý = 'ý',
        //KEY_þ = 'þ',
        //KEY_ÿ = 'ÿ',
        //KEY_Ā = 'Ā',
        //KEY_ā = 'ā',
        //KEY_Ă = 'Ă',
        //KEY_ă = 'ă',
        //KEY_Ą = 'Ą',
        //KEY_ą = 'ą',
        //KEY_Ć = 'Ć',
        //KEY_ć = 'ć',
        //KEY_Ĉ = 'Ĉ',
        //KEY_ĉ = 'ĉ',
        //KEY_Ċ = 'Ċ',
        //KEY_ċ = 'ċ',
        //KEY_Č = 'Č',
        //KEY_č = 'č',
        //KEY_Ď = 'Ď',
        //KEY_ď = 'ď',
        //KEY_Đ = 'Đ',
        //KEY_đ = 'đ',
        //KEY_Ē = 'Ē',
        //KEY_ē = 'ē',
        //KEY_Ĕ = 'Ĕ',
        //KEY_ĕ = 'ĕ',
        //KEY_Ė = 'Ė',
        //KEY_ė = 'ė',
        //KEY_Ę = 'Ę',
        //KEY_ę = 'ę',
        //KEY_Ě = 'Ě',
        //KEY_ě = 'ě',
        //KEY_Ĝ = 'Ĝ',
        //KEY_ĝ = 'ĝ',
        //KEY_Ğ = 'Ğ',
        //KEY_ğ = 'ğ',
        //KEY_Ġ = 'Ġ',
        //KEY_ġ = 'ġ',
        //KEY_Ģ = 'Ģ',
        //KEY_ģ = 'ģ',
        //KEY_Ĥ = 'Ĥ',
        //KEY_ĥ = 'ĥ',
        //KEY_Ħ = 'Ħ',
        //KEY_ħ = 'ħ',
        //KEY_Ĩ = 'Ĩ',
        //KEY_ĩ = 'ĩ',
        //KEY_Ī = 'Ī',
        //KEY_ī = 'ī',
        //KEY_Ĭ = 'Ĭ',
        //KEY_ĭ = 'ĭ',
        //KEY_Į = 'Į',
        //KEY_į = 'į',
        //KEY_İ = 'İ',
        //KEY_ı = 'ı',
        //KEY_Ĳ = 'Ĳ',
        //KEY_ĳ = 'ĳ',
        //KEY_Ĵ = 'Ĵ',
        //KEY_ĵ = 'ĵ',
        //KEY_Ķ = 'Ķ',
        //KEY_ķ = 'ķ',
        //KEY_ĸ = 'ĸ',
        //KEY_Ĺ = 'Ĺ',
        //KEY_ĺ = 'ĺ',
        //KEY_Ļ = 'Ļ',
        //KEY_ļ = 'ļ',
        //KEY_Ľ = 'Ľ',
        //KEY_ľ = 'ľ',
        //KEY_Ŀ = 'Ŀ',
        //KEY_ŀ = 'ŀ',
        //KEY_Ł = 'Ł',
        //KEY_ł = 'ł',
        //KEY_Ń = 'Ń',
        //KEY_ń = 'ń',
        //KEY_Ņ = 'Ņ',
        //KEY_ņ = 'ņ',
        //KEY_Ň = 'Ň',
        //KEY_ň = 'ň',
        //KEY_ŉ = 'ŉ',
        //KEY_Ŋ = 'Ŋ',
        //KEY_ŋ = 'ŋ',
        //KEY_Ō = 'Ō',
        //KEY_ō = 'ō',
        //KEY_Ŏ = 'Ŏ',
        //KEY_ŏ = 'ŏ',
        //KEY_Ő = 'Ő',
        //KEY_ő = 'ő',
        //KEY_Œ = 'Œ',
        //KEY_œ = 'œ',
        //KEY_Ŕ = 'Ŕ',
        //KEY_ŕ = 'ŕ',
        //KEY_Ŗ = 'Ŗ',
        //KEY_ŗ = 'ŗ',
        //KEY_Ř = 'Ř',
        //KEY_ř = 'ř',
        //KEY_Ś = 'Ś',
        //KEY_ś = 'ś',
        //KEY_Ŝ = 'Ŝ',
        //KEY_ŝ = 'ŝ',
        //KEY_Ş = 'Ş',
        //KEY_ş = 'ş',
        //KEY_Š = 'Š',
        //KEY_š = 'š',
        //KEY_Ţ = 'Ţ',
        //KEY_ţ = 'ţ',
        //KEY_Ť = 'Ť',
        //KEY_ť = 'ť',
        //KEY_Ŧ = 'Ŧ',
        //KEY_ŧ = 'ŧ',
        //KEY_Ũ = 'Ũ',
        //KEY_ũ = 'ũ',
        //KEY_Ū = 'Ū',
        //KEY_ū = 'ū',
        //KEY_Ŭ = 'Ŭ',
        //KEY_ŭ = 'ŭ',
        //KEY_Ů = 'Ů',
        //KEY_ů = 'ů',
        //KEY_Ű = 'Ű',
        //KEY_ű = 'ű',
        //KEY_Ų = 'Ų',
        //KEY_ų = 'ų',
        //KEY_Ŵ = 'Ŵ',
        //KEY_ŵ = 'ŵ',
        //KEY_Ŷ = 'Ŷ',
        //KEY_ŷ = 'ŷ',
        //KEY_Ÿ = 'Ÿ',
        //KEY_Ź = 'Ź',
        //KEY_ź = 'ź',
        //KEY_Ż = 'Ż',
        //KEY_ż = 'ż',
        //KEY_Ž = 'Ž',
        //KEY_ž = 'ž',
        //KEY_ſ = 'ſ',
        //KEY_ƀ = 'ƀ',
        //KEY_Ɓ = 'Ɓ',
        //KEY_Ƃ = 'Ƃ',
        //KEY_ƃ = 'ƃ',
        //KEY_Ƅ = 'Ƅ',
        //KEY_ƅ = 'ƅ',
        //KEY_Ɔ = 'Ɔ',
        //KEY_Ƈ = 'Ƈ',
        //KEY_ƈ = 'ƈ',
        //KEY_Ɖ = 'Ɖ',
        //KEY_Ɗ = 'Ɗ',
        //KEY_Ƌ = 'Ƌ',
        //KEY_ƌ = 'ƌ',
        //KEY_ƍ = 'ƍ',
        //KEY_Ǝ = 'Ǝ',
        //KEY_Ə = 'Ə',
        //KEY_Ɛ = 'Ɛ',
        //KEY_Ƒ = 'Ƒ',
        //KEY_ƒ = 'ƒ',
        //KEY_Ɠ = 'Ɠ',
        //KEY_Ɣ = 'Ɣ',
        //KEY_ƕ = 'ƕ',
        //KEY_Ɩ = 'Ɩ',
        //KEY_Ɨ = 'Ɨ',
        //KEY_Ƙ = 'Ƙ',
        //KEY_ƙ = 'ƙ',
        //KEY_ƚ = 'ƚ',
        //KEY_ƛ = 'ƛ',
        //KEY_Ɯ = 'Ɯ',
        //KEY_Ɲ = 'Ɲ',
        //KEY_ƞ = 'ƞ',
        //KEY_Ɵ = 'Ɵ',
        //KEY_Ơ = 'Ơ',
        //KEY_ơ = 'ơ',
        //KEY_Ƣ = 'Ƣ',
        //KEY_ƣ = 'ƣ',
        //KEY_Ƥ = 'Ƥ',
        //KEY_ƥ = 'ƥ',
        //KEY_Ʀ = 'Ʀ',
        //KEY_Ƨ = 'Ƨ',
        //KEY_ƨ = 'ƨ',
        //KEY_Ʃ = 'Ʃ',
        //KEY_ƪ = 'ƪ',
        //KEY_ƫ = 'ƫ',
        //KEY_Ƭ = 'Ƭ',
        //KEY_ƭ = 'ƭ',
        //KEY_Ʈ = 'Ʈ',
        //KEY_Ư = 'Ư',
        //KEY_ư = 'ư',
        //KEY_Ʊ = 'Ʊ',
        //KEY_Ʋ = 'Ʋ',
        //KEY_Ƴ = 'Ƴ',
        //KEY_ƴ = 'ƴ',
        //KEY_Ƶ = 'Ƶ',
        //KEY_ƶ = 'ƶ',
        //KEY_Ʒ = 'Ʒ',
        //KEY_Ƹ = 'Ƹ',
        //KEY_ƹ = 'ƹ',
        //KEY_ƺ = 'ƺ',
        //KEY_ƻ = 'ƻ',
        //KEY_Ƽ = 'Ƽ',
        //KEY_ƽ = 'ƽ',
        //KEY_ƾ = 'ƾ',
        //KEY_ƿ = 'ƿ',
        //KEY_ǀ = 'ǀ',
        //KEY_ǁ = 'ǁ',
        //KEY_ǂ = 'ǂ',
        //KEY_ǃ = 'ǃ',
        //KEY_Ǆ = 'Ǆ',
        //KEY_ǅ = 'ǅ',
        //KEY_ǆ = 'ǆ',
        //KEY_Ǉ = 'Ǉ',
        //KEY_ǈ = 'ǈ',
        //KEY_ǉ = 'ǉ',
        //KEY_Ǌ = 'Ǌ',
        //KEY_ǋ = 'ǋ',
        //KEY_ǌ = 'ǌ',
        //KEY_Ǎ = 'Ǎ',
        //KEY_ǎ = 'ǎ',
        //KEY_Ǐ = 'Ǐ',
        //KEY_ǐ = 'ǐ',
        //KEY_Ǒ = 'Ǒ',
        //KEY_ǒ = 'ǒ',
        //KEY_Ǔ = 'Ǔ',
        //KEY_ǔ = 'ǔ',
        //KEY_Ǖ = 'Ǖ',
        //KEY_ǖ = 'ǖ',
        //KEY_Ǘ = 'Ǘ',
        //KEY_ǘ = 'ǘ',
        //KEY_Ǚ = 'Ǚ',
        //KEY_ǚ = 'ǚ',
        //KEY_Ǜ = 'Ǜ',
        //KEY_ǜ = 'ǜ',
        //KEY_ǝ = 'ǝ',
        //KEY_Ǟ = 'Ǟ',
        //KEY_ǟ = 'ǟ',
        //KEY_Ǡ = 'Ǡ',
        //KEY_ǡ = 'ǡ',
        //KEY_Ǣ = 'Ǣ',
        //KEY_ǣ = 'ǣ',
        //KEY_Ǥ = 'Ǥ',
        //KEY_ǥ = 'ǥ',
        //KEY_Ǧ = 'Ǧ',
        //KEY_ǧ = 'ǧ',
        //KEY_Ǩ = 'Ǩ',
        //KEY_ǩ = 'ǩ',
        //KEY_Ǫ = 'Ǫ',
        //KEY_ǫ = 'ǫ',
        //KEY_Ǭ = 'Ǭ',
        //KEY_ǭ = 'ǭ',
        //KEY_Ǯ = 'Ǯ',
        //KEY_ǯ = 'ǯ',
        //KEY_ǰ = 'ǰ',
        //KEY_Ǳ = 'Ǳ',
        //KEY_ǲ = 'ǲ',
        //KEY_ǳ = 'ǳ',
        RSHIFT,
        LCONTROL,
        RCONTROL,
        LSHIFT,
        NUMLOCK,
        F24,
        BACK,
        F23,
        F22,
        F21,
        F20,
        F19,
        F18,
        F17,
        F16,
        F15,
        F14,
        F13,
        F12,
        F11,
        F10,
        F9,
        F8,
        F7,
        F6,
        F5,
        F4,
        F3,
        F2,
        F1,
        DIVIDE,
        DECIMAL,
        SUBTRACT,
        SEPARATOR,
        ADD,
        MULTIPLY,
        NUMPAD_9,
        NUMPAD_8,
        NUMPAD_7,
        NUMPAD_5,
        NUMPAD_6,
        NUMPAD_4,
        NUMPAD_3,
        NUMPAD_2,
        NUMPAD_1,
        NUMPAD_0,
        KEY_Z,
        KEY_Y,
        KEY_X,
        KEY_W,
        KEY_V,
        KEY_U,
        KEY_T,
        KEY_S,
        KEY_R,
        KEY_Q,
        KEY_O,
        KEY_P,
        KEY_N,
        KEY_M,
        KEY_L,
        KEY_K,
        KEY_J,
        KEY_I,
        KEY_H,
        KEY_G,
        KEY_F,
        KEY_E,
        KEY_D,
        KEY_C,
        KEY_B,
        KEY_A,
        KEY_9,
        KEY_8,
        KEY_7,
        KEY_6,
        KEY_5,
        KEY_4,
        KEY_3,
        KEY_2,
        KEY_1,
        KEY_0,
        DELETE,
        INSERT,
        PRINT,
        SELECT,
        DOWN,
        RIGHT,
        UP,
        LEFT,
        HOME,
        END,
        SPACE,
        ESCAPE,
        PAUSE,
        MENU,
        CONTROL,
        SHIFT,
        RETURN,
        CLEAR,
        TAB,
    }
}
