/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTSystemVersion */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTSystemVersion
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTSystemVersion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTSystemVersion
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTSystemVersion_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTSystemVersion
 * Method:    GetVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTSystemVersion_GetVersionString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
