/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTKeyboard */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTKeyboard
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTKeyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTKeyboard
 * Method:    pressKey
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTKey;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTKeyboard_pressKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTKeyboard
 * Method:    releaseKey
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTKey;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTKeyboard_releaseKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTKeyboard
 * Method:    clickKey
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTKey;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTKeyboard_clickKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTKeyboard
 * Method:    type
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTKeyboard_type
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
