/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTVector2i */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTVector2i
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTVector2i
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    setup
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_setup
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    getLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_getLength
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    equals
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_equals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    getArea
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_getArea
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    add
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    subtract
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_subtract
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    divide
 * Signature: (I)Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_divide__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTVector2i
 * Method:    divide
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTVector2i_divide__Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2i_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
