/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_filomilo_GuiTestingLibrary_Native_JGTWindow */

#ifndef _Included_org_filomilo_GuiTestingLibrary_Native_JGTWindow
#define _Included_org_filomilo_GuiTestingLibrary_Native_JGTWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetPosition
 * Signature: ()Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetPosition
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetSize
 * Signature: ()Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetSize
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    DoesExist
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_DoesExist
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetName
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    IsMinimized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_IsMinimized
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    MoveWindow
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_MoveWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    Minimize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_Minimize
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    Maximize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_Maximize
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetProcessOfWindow
 * Signature: ()Lorg/filomilo/GuiTestingLibrary/Native/JGTProcess;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetProcessOfWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_Close
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    SetWindowSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_SetWindowSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    SetPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_SetPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    BringUpFront
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_BringUpFront
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    SizeShouldBe
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_SizeShouldBe
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    ShouldWindowExist
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_ShouldWindowExist
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    KillProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_KillProcess
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    ShouldBeMinimized
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_ShouldBeMinimized
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetWindowName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetWindowName
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetWindowContentPosition
 * Signature: ()Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetWindowContentPosition
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetWindowContentSize
 * Signature: ()Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetWindowContentSize
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetContentPixelColorAt
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)Lorg/filomilo/GuiTestingLibrary/Native/JGTColor;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetContentPixelColorAt__Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2i_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetContentPixelColorAt
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;)Lorg/filomilo/GuiTestingLibrary/Native/JGTColor;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetContentPixelColorAt__Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2f_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    ContentPixelAtShouldBeColor
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;Lorg/filomilo/GuiTestingLibrary/Native/JGTColor;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_ContentPixelAtShouldBeColor__Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2i_2Lorg_filomilo_GuiTestingLibrary_Native_JGTColor_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    CenterWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_CenterWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    WindowNameShouldBe
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_WindowNameShouldBe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    ContentPixelAtShouldBeColor
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2f;Lorg/filomilo/GuiTestingLibrary/Native/JGTColor;I)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_ContentPixelAtShouldBeColor__Lorg_filomilo_GuiTestingLibrary_Native_JGTVector2f_2Lorg_filomilo_GuiTestingLibrary_Native_JGTColor_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetScreenshot
 * Signature: ()Lorg/filomilo/GuiTestingLibrary/Native/JGTScreenshot;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetScreenshot
  (JNIEnv *, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetScreenshotRect
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)Lorg/filomilo/GuiTestingLibrary/Native/JGTScreenshot;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetScreenshotRect
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    GetPixelColorAt
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;)Lorg/filomilo/GuiTestingLibrary/Native/JGTColor;
 */
JNIEXPORT jobject JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_GetPixelColorAt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_filomilo_GuiTestingLibrary_Native_JGTWindow
 * Method:    PixelAtShouldBeColor
 * Signature: (Lorg/filomilo/GuiTestingLibrary/Native/JGTVector2i;Lorg/filomilo/GuiTestingLibrary/Native/JGTColor;)V
 */
JNIEXPORT void JNICALL Java_org_filomilo_GuiTestingLibrary_Native_JGTWindow_PixelAtShouldBeColor
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
